- name: Sync tijdelijke directory met /etc/squid
  shell: rsync -av /tmp/squid/ /etc/squid/
  become: true 
- name: Check and reload Squid
  block:
    - name: Check squid syntax
      shell: squid -k parse
      register: squidout
      failed_when: false
      no_log: True
    - ansible.builtin.set_fact:
        squidparse_err: "{{ squidout.stderr_lines|select('regex', '.*WARNING.*|.*ERROR.*|.*FATAL.*')|list }}"
      failed_when: (squidparse_err | length > 0)
    - name: Reload squid
      shell: systemctl reload squid
      become: true 
      ignore_errors: True
    - name: Reload squid configuration
      shell: systemctl reload squid
      become: true 
      register: reload_squid
      #failed_when: reload_squid.rc != 0
  rescue:
    - name: Restore backup in case of error
      shell: tar -xf /tmp/squidconf.tar -C /
      become: true 
    - name: Restart old squid config when reload unsuccesful
      shell: systemctl restart squid
      become: true 
      timeout: 35
      when: (reload_squid is defined) and (reload_squid.rc != 0)
    - name: Remove backup
      shell: rm /tmp/squidconf.tar
      become: true 
    - name: Fail playbook in case of errors
      debug: msg="Updating squid failed, please check output."
      failed_when: true
- name: Remove backup
  shell: rm /tmp/squidconf.tar
  become: true 
