- name: restart_snmpsrvs
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
  with_items: "{{ snmpdepservices }}"
- name: restart_zbxservices
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  with_items: "{{ zbxservices }}"
- name: restart_mariadb
  ansible.builtin.service:
    name: mariadb
    state: "restarted"
    enabled: true
