- name: Test zabbix
  hosts: zabbixservers
  gather_facts: no
  vars:
    test1: "test1"
    test2: "{{ test1}}"

  tasks:
  - name: Loop over subelements of the dictionary
    debug: msg="test2={{ test2 }}"
