- name: Test zabbix
  hosts: zabbixservers
  gather_facts: no
  become: true

  tasks:
  - name: Loop over subelements of the dictionary
    debug: msg="Key={{ item.key }} value={{ item.value }}"
    with_dict: "{{ zabbixconf }}"