- name: Test zabbix
  hosts: zabbixservers
  gather_facts: no
  vars:
    test1: "test1"
    test2: "{{ test1}}"

  tasks:
  - name: Loop over subelements of the dictionary
    debug: msg="test2={{ test2 }}"
  - name: Make directories for mibs
    ansible.builtin.file:
      path: "/var/lib/snmp/mibs/{{ item.path }}"
      state: directory
      mode: "755"
      owner: root
      group: root
    with_filetree: "/var/lib/snmp/mibs/"
    when: item.state=='directory'
    no_log: true
  - name: Copy snmp mib files
    ansible.builtin.copy:
      src: "/var/lib/snmp/mibs/{{ item.path }}"
      dest: "/var/lib/snmp/mibs/{{ item.path }}"
      mode: "644"
      owner: "root"
      group: "root"
    with_filetree: "/var/lib/snmp/mibs/"
    when: item.state=='file'
    no_log: true
  - name: task 1
    command: echo task1
    register: task_result_1
  - name: task 2
    command: echo task2
    register: task_result_2
  - name: task 3
    command: echo task3
    register: task_result_3

  - name: show results
    debug:
      msg: "Gewijzigd"
    when: task_result_1.changed or task_result_2.changed or task_result_3.changed
