---
  - name: Install and configure zabbix servers and proxies
    hosts: zabbix
    become: true
    handlers:
      - name: Import global handlers for restarting services
        # You can also look at include_tasks: handlers.yml
        import_tasks: global_handlers.yml
    tasks:
      - name: Install base packages for all servers and proxies
        ansible.builtin.dnf:
          name: "{{ packages }}"
          state: present
      - name: Configure SNMP trap daemon
        ansible.builtin.lineinfile:
          path: /etc/snmp/snmptrapd.conf
          line: "{{ item }}"
        loop: 
          - "authCommunity execute publicmindef"
          - "perl do \"/var/lib/zabbix/zabbix_trap_receiver.pl\";"
        no_log: true
        notify: restart_snmptrapd
      - name: Create a zabbix home directory if it does not exist
        ansible.builtin.file:
          path: "{{ zabbixhome }}"
          state: directory
          owner: zabbix
          group: zabbix
          mode: '0755'
      - name: Install base zabbix files
        ansible.builtin.copy:
          src: "{{ item.filename }}"
          dest: "{{ item.filedestination }}"
          owner: "{{ item.fileowner }}"
          group: "{{ item.filegroup }}"
          mode: "{{ item.filemode }}"
        loop:
          "{{ zabbixfiles }}"
      - name: Start and enable generic services
        ansible.builtin.service:
          name: "{{ item }}"
          state: started
          enabled: true
        loop: 
          "{{ zabbixservices }}"
      - name: Install and configure database servers
        include_role:
          name: zabbixdb
        when: "'zabbixdbservers' in group_names"
      - name: Install and configure servers
        include_role:
          name: zabbixserver
        when: "'zabbixservers' in group_names"
      - name: Install and configure proxies
        include_role:
          name: zabbixproxy
        when: "'zabbixproxies' in group_names"
      - name: Create tar on local server from MIB directory
        community.general.archive:
          path: /var/lib/snmp/mibs/
          dest: /tmp/snmpmibs.tgz
          format: gz
        run_once: true
        delegate_to: localhost
        become: false
      - name: Extract SNMP MIB tar file
        ansible.builtin.unarchive:
          src: /tmp/snmpmibs.tgz
          dest: /var/lib/snmp/mibs/
        notify: restart_snmpsrvs


