all:
  children:
    virtualmachines:
      hosts:
        ansibleclient.lan:
      vars:
        sslports:
          - 443
          - 8080
        local_log: yes
        ports:
          management: 
          - port: 8080
            options: ""
          productie:
          - port: 8080
            options: ""          
          - port: 443
            options: "accel"
        ICAP: no
    cenbo_cug5:
      hosts:
        ansibleclient.lan: 
    squidservers:
      hosts:
        localhost: 
          ansible_connection: local
          #ansible_ssh_private_key_file: ~/.ssh/ansible
      vars:
        sslports:
          - 443
          - 8080
        local_log: yes
        ports: 
          - port: 8080
            options: ""
          - port: 443
            options: "accel"
    zabbixservers:
      hosts:
        zabbix60.lan
          
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: "/"
        ansible_host: zabbix60.lan

