all:
  children:
    virtualmachines:
      hosts:
        ansibleclient.lan
    squidservers:
      hosts:
        localhost: 
          connection: local
          #ansible_ssh_private_key_file: ~/.ssh/ansible
      vars:
        ports: 
          - port: 8080
            options: ""
          - port: 443
            options: "accel"

