all:
  children:
    virtualmachines:
      hosts:
        ansibleclient.lan:
      vars:
        sslports:
          - 443
          - 8080
        local_log: yes
        ports:
          management: 
          - port: 8080
            options: ""
          productie:
          - port: 8080
            options: ""          
          - port: 443
            options: "accel"
        ICAP: no
    squidtest:
      hosts:
        ansibleclient.lan: 
    squidservers:
      hosts:
        localhost: 
          ansible_connection: local
          #ansible_ssh_private_key_file: ~/.ssh/ansible
      vars:
        sslports:
          - 443
          - 8080
        local_log: yes
        ports: 
          - port: 8080
            options: ""
          - port: 443
            options: "accel"

