all:
  children:
    zabbix:
      hosts:
        zabbixserver.lan:
        zabbixproxy.lan:
      vars:
        packages:
          - zabbix-selinux-policy 
          - net-snmp
          - net-snmp-perl
          - net-snmp-utils
          - zabbix-agent
        zabbixfiles:
          - filename: zabbix_trap_receiver.pl
            filedestination: /var/lib/zabbix/zabbix_trap_receiver.pl
            fileowner: root
            filegroup: root
            filemode: '0750'
        zabbixservices:
          - snmptrapd
        SNMPTrapperFile: /var/log/snmptrap/snmptrap.log
        dbpasswd: DBS3cr3t
        zabbixhome: /var/lib/zabbix
    zabbixservers:
      hosts:
        zabbixserver.lan:
          dbhost: localhost
      vars:
        serverpackages:
          - zabbix-server-mysql 
          - zabbix-web-mysql 
          - zabbix-apache-conf 
          - zabbix-selinux-policy 
        mysql_password: heelmoeilijkwachtwoord1234
        serverconf:
          DBHost: "{{ dbhost }}"
          DBName: zabbix
          DBUser: zabbix
          DBPassword: "{{ dbpasswd }}"
          SNMPTrapperFile: "{{ SNMPTrapperFile }}"
          StartSNMPTrapper: "1"
          AllowUnsupportedDBVersions: "1"
        serverconffile: /etc/zabbix/zabbix_server.conf
        zbxservices:
          - httpd
          - zabbix-server
        snmpdepservices:
          - zabbix-server
          - snmptrapd
    zabbixdbservers:
      hosts:
        zabbixserver.lan
      vars:
        dbserverpackages:
          - zabbix-server-mysql 
          - zabbix-sql-scripts 
          - zabbix-selinux-policy 
          - mariadb-server
          - python3-PyMySQL
        dbpasswd: DBS3cr3t
        mysql_password: heelmoeilijkwachtwoord1234
    zabbixproxies:
      hosts:
        zabbixproxy.lan:
          #proxymode: 0=active, 1=passive
          proxymode: "0"
          zabbixserver: zabbixserver.lan
      vars:
        proxypackages:
          - zabbix-proxy-sqlite3
          - zabbix-agent
        proxyconf:
          SNMPTrapperFile: "{{ SNMPTrapperFile }}"
          StartSNMPTrapper: 1
          DBName: "{{ zabbixhome }}/zabbixproxy.sqlite"
          Server: "{{ zabbixserver }}"
          ProxyMode: "{{ proxymode }}"
        proxyconffile: /etc/zabbix/zabbix_proxy.conf
        snmpdepservices:
          - zabbix-proxy
          - snmptrapd
        zbxservices:
          - httpd
          - zabbix-proxy
      