- name: Install Zabbix server packages
  ansible.builtin.dnf:
    name: "{{ proxypackages }}"
    state: present
  notify: restart_zbxservices
- name: Modify Zabbix configuration file
  ansible.builtin.lineinfile:
    path: "{{ proxyconffile }}"
    regexp: '(^# |^){{ item.key }}'
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ proxyconf }}"
  no_log: true
  notify: restart_zbxservices
