- name: Install Zabbix server packages
  ansible.builtin.dnf:
    name: "{{ proxypackages }}"
    state: present
- name: Modify Zabbix configuration file
  ansible.builtin.lineinfile:
    path: "{{ proxyconffile }}"
    regexp: '(^# |^){{ item.key }}'
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ proxyconf }}"
  no_log: true
- name: Start Proxy
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: 
    - zabbix-proxy
