- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /tmp/squid/conf.d
    state: directory
    mode: '0755'
- name: Maak forward proxy configuraties voor squid servers
  ansible.builtin.template:
    src: forwardproxy.j2
    dest: /tmp/squid/conf.d/000_forwardproxy.conf
